<?php return [
  'default_theme' => 'simplify',
  'default_lang' => 'zh-cn',
  'settings' => 'cogs',
  'theme' => 'dashboard',
  'category' => 'reorder',
  'content' => 'edit',
  'user' => 'group',
  'wechat' => 'comments',
  'mall' => 'shopping-cart',
  'expand' => 'wrench',
  'sys_version' => '0.2.5 Alpha 1737',
  'USER_AUTH_ON' => 1,
  'USER_AUTH_TYPE' => 2,
  'USER_AUTH_KEY' => 'USER_ID',
  'ADMIN_AUTH_KEY' => 'ADMIN_ID',
  'USER_AUTH_GATEWAY' => 'account/login',
  'NOT_AUTH_MODULE' => 'Account',
  'NOT_AUTH_ACTION' => 'login,verify',
  'RBAC_ROLE_TABLE' => 'np_role',
  'RBAC_USER_TABLE' => 'np_role_admin',
  'RBAC_ACCESS_TABLE' => 'np_access',
  'RBAC_NODE_TABLE' => 'np_node',
  'sys_v' => 'Alpha内测版 Demo演示版 Beta公测版 Stable稳定版 Release正式版'
];